name: Pull Request Checker

on:
  pull_request:
    branches:
      - main

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, world!"
